name: payslip_app
description: Minimalist Payslip Generator

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  url_launcher: ^6.1.11
  file_picker: ^8.1.2
  share_plus: ^11.0.0
  pdfx: ^2.6.0
  syncfusion_flutter_pdfviewer: ^30.1.42
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
